### ISSUE TITLE
De-allocation logic

### ISSUE THREAD

**Issue by cygnusv** [threshold-network/solidity-contracts#13]
@vzotova and I have been thinking about the specifics of the staking contract with respect to application allocations, and we have some questions. First, let's settle on some terminology for the moment:

- **Allocate**: Assign an amount of $T that belongs to a T stake (or equivalent legacy stake in $NU/$KEEP) to a T application. There's no allocation overlapping (i.e., you can't reuse the same portion of stake to different applications)
- **De-allocate**: Taking back an allocation from an application. There are 2 types of de-allocation:
    - **Cancel allocation**: The allocated amount that's being taken back is not allocated elsewhere
    - **Switch allocation**: The allocated amount is moved to a different application

We think that there should be different rules governing canceling and switching allocations: there are different intentions in someone moving $T from PRE to tBTC apps than from someone simply wanting to withdraw. In other words, switching allocations should be less restrictive than cancelling allocations. Also, we think that this rules would probably be different _per application_ (e.g., it may be different to de-allocate from PRE than de-allocating from tBTC), for instance, in terms of the effective time to de-allocate.

What do you think about this? With respect to tBTCv2, how does this look like? Do you see different rules about cancelling and switching allocations from tBTC to another T application?

Another related question is about _partial de-allocations_, in terms of amount of tokens being de-allocated. We don't see any different from full de-allocations from the perspective of the PRE application, but what about tBTCv2? Whats the process like for a staker wanting to, say, de-allocate half of their tBTCv2 stake allocation?

**Comment by pdyraga** [comment]
Are we good about closing this issue now @cygnusv?
