### ISSUE TITLE
Deploy canonical contract on Solana

### ISSUE THREAD

**Issue by erdogan** [threshold-network/solidity-contracts#146]
- [ ] Implement canonical SolanaTBTC 
- [ ] Implement WormholeGateway that integrates SolanaTBTC
- [ ] Add deployment scripts for devnet and mainnet. Execute mappings of other chains.
- [ ] Let the xLab team know about new contracts on devnet and start testing when their integration is done in Portal.
- [ ] Deploy to mainnet and testing.

**Comment by pdyraga** [comment]
Closing in favor of more focused issues in the `keep-network/tbtc-v2` repo where the code will be located: https://github.com/keep-network/tbtc-v2/issues/656, https://github.com/keep-network/tbtc-v2/issues/658, https://github.com/keep-network/tbtc-v2/issues/659.
