### ISSUE TITLE
Extend IApplication to generalize tBTC, RandomBeacon and TACo apps

### ISSUE THREAD

**Issue by cygnusv** [threshold-network/solidity-contracts#156]
In addition to the discussion on #88, while developing the TACo app contract, and particularly when integrating it with the dashboard, we've detected several methods that should be generalized in `IApplication` due to common workflows. This is specially relevant in contexts that consume the 3 contracts (i.e. the dashboard).

Also, consider if it's necessary the creation of an additional interface for Threshold apps that assume the existence of an operator role, something like `IApplicationWithOperator`, so we can abstract here methods like `registerOperator()`.

**Comment by theref** [comment]
When bonding an operator, Keep do:
```
function registerOperator(Data storage self, address operator) public {
        address stakingProvider = msg.sender;
```

a) it's called registerOperator
b) it only takes the operator as a parameter, msg.sender must be the associated stakingProvider

For Nucypher:
```
function bondOperator(
        address _stakingProvider,
        address _operator
    ) external onlyOwnerOrStakingProvider(_stakingProvider) 
```
we have the idea of an Owner as well as stakingProvider so it's a bit more complicated.

It would be ideal if we could bring this inline with Keep, certain areas of the dashboard are built very tightly around their Application Interface https://github.com/threshold-network/token-dashboard/blob/8652343fd254666e04bc90c601e4452c06c3fc38/src/threshold-ts/applications/index.ts#L82

**Comment by lukasz-zimnoch** [comment]
Looks like the `IApplication` interface in the dashboard went a little bit too far. I think we should extract Keep-specific parts to a sub-interface:
```
export interface IApplication {
    // Only methods from https://github.com/threshold-network/solidity-contracts/blob/main/contracts/staking/IApplication.sol
}

export interface IWalletRegistry extends IApplication {
    // Methods specific to https://github.com/keep-network/keep-core/blob/324f66fb3f1003f6cfeb7d4149ae3f1d902dba2e/solidity/ecdsa/contracts/WalletRegistry.sol#L37
}
```
This way the actual contracts structure is reflected and you can easily add:
```
interface ITaco extends IApplication {
    // Whatever you need.
}
```
cc @michalsmiarowski
