### ISSUE TITLE
Slashing queue

### ISSUE THREAD

**Issue by eth-r** [threshold-network/solidity-contracts#16]
To keep stakes synchronised between applications when operators are slashed, without the risk of running out of gas, we could queue up slashings and let users process the transactions:

When an application slashes one or more operators, it adds them to the _slashing queue_ on the staking contract. A queue entry contains the operator's address and the amount they're due to be slashed.

When there is at least one operator in the slashing queue, any account can submit a transaction processing one or more operators' slashings, and collecting a reward for doing so. A queued slashing is processed by updating the operator's stake to the post-slashing amount, and notifying all affected applications that the operator's authorised stake has been reduced due to slashing. The application must then do the necessary adjustments (such as removing the operator from the sortition pool or reducing its weight; changing the operator's eligibility for rewards; etc.).

This technically has an unbounded iteration, but it is unlikely to be troublesome; allowing a fairly generous 250k gas for each application to adjust, even 10 applications would only cost 2.5M gas per operator permitting the processing of 3 operators' slashings in a single block. On the other hand, adding 100 operators to the slashing queue would only cost around 2M gas, making it possible to slash large groups at once.

Open questions:

Should the queue be processed on a first-in, first-out basis, or should users be able to pick specific operators' slashings to process?

How to deal with operators who get slashed multiple times before the first slashing is processed? Should we combine the slashings? If we do, how do we distribute seized tokens, especially if the applications try to slash the operator more than their stake is worth?

How to deal with operators whose stake has fallen to zero, and whose processing thus can't be rewarded by seizing tokens for the submitter of the processing transaction? Should we take some kind of a tax to pay for the slashing processing instead of seizing slashed tokens for the processer?

How to deal with operators who get slashed on the KEEP legacy staking contract instead of the T staking contract?

**Comment by cygnusv** [comment]
> How to deal with operators who get slashed on the KEEP legacy staking contract instead of the T staking contract?

My understanding is that authorizations on the KEEP legacy side will go through the T staking contract, so it shouldn't be possible to slash a KEEP legacy stake directly, but through T. @pdyraga Can you confirm?

**Comment by eth-r** [comment]
The problem is not them getting slashed through the T contract, but directly on the KEEP contract outside the slashing queue and getting the T contract out of sync (related to #14 but regarding slashing on KEEP rather than undelegation)

**Comment by pdyraga** [comment]
> Should the queue be processed on a first-in, first-out basis, or should users be able to pick specific operators' slashings to process?

> How to deal with operators whose stake has fallen to zero, and whose processing thus can't be rewarded by seizing tokens for the submitter of the processing transaction? Should we take some kind of a tax to pay for the slashing processing instead of seizing slashed tokens for the processer?

If we implement the slashing queue as FIFO, isn't this problem solved for us? One can benefit from processing the slashing of other operators but sometimes there is some work that needs to be done voluntarily. FIFO does not solve the case when operator slashed to zero is the last one to be processed but if we make all clients process slashing automatically, it should be solved.

> How to deal with operators who get slashed on the KEEP legacy staking contract instead of the T staking contract?

In practice, the only case for that is when they committed a fraud by reconstructing a public key in 3-of-3 mode. If they committed the fraud, it's their problem to update the stake.

> How to deal with operators who get slashed multiple times before the first slashing is processed? Should we combine the slashings? If we do, how do we distribute seized tokens, especially if the applications try to slash the operator more than their stake is worth?

Feels like not worth the complexity given the slashing happens rarely and the queue should be processed before the next slashing happens. The application could provide slashing amount per address to make it more gas efficient for ones processing the queue (`address[], uint256[]`).

**Comment by eth-r** [comment]
> Feels like not worth the complexity given the slashing happens rarely and the queue should be processed before the next slashing happens. The application could provide slashing amount per address to make it more gas efficient for ones processing the queue (`address[], uint256[]`).

I think we might be able to get away with `struct Slashing { address operator, uint96 amount }` which should halve the cost;

18 decimals is roughly 2^60 leaving 2^36 for the integers, and 10B T is a bit over 2^33 so any actual T amount should be possible to encode without losing precision

**Comment by cygnusv** [comment]
> I think we might be able to get away with `struct Slashing { address operator, uint96 amount }` which should halve the cost;

We already use `uint96` to store T amounts in other places (e.g., T token's checkpoints for voting), so this should be OK.

**Comment by eth-r** [comment]
Something we need to note in the implementation:

When one or more operators are added to the slashing queue and the notifier is rewarded, we need to query the stake for each operator (including the legacy KEEP/NU stake) and only slash what is available. Then we record the post-slashing stake of the operator in the staking contract and add the actually slashed amount into the slashing queue. This ensures that the bookkeeping stays consistent even if the notifier is paid out immediately. If we don't do this, we either can't pay the notifier right away (and have to add the notifier address to the slashing queue entries, almost doubling the cost) or we risk getting into a state where the staking contract doesn't hold all the tokens it thinks it does, rendering it insolvent.

**Comment by vzotova** [comment]
I agree that with simple approach we can easily have inconsistent state. 
What do you mean by `slash what is available`? If executing real slash tx then we will return to situation with unsynced state between staking contract and apps, or I'm just missing something.
Also I too don't fully like to pay notifier 1% from slashing during `processSlashing`. Mostly because `seize` in keep and nucypher contracts accept only one address for reward so in that case it will lead to some logic to transfer reward to the notifier and who executes `processSlashing` tx.
What would you all say about pay notifier right away but not from slashing amount but from some treasury pool in T tokens (fixed amount per operator)? In that case it will simplify relation between notifying slashing and processing. As downside: maintance treasury in staking contract for notifiers, but even in that situation we can replenish it from slashed T amount (instead of burning this amount).
