### ISSUE TITLE
Can't convert Nu to T

### ISSUE THREAD

**Issue by Wangj20036** [threshold-network/solidity-contracts#169]
Dear Threshold network,

I tried to use your webpage to convert my nucypher to T (https://dashboard.threshold.network/upgrade/nu), but it failed. Everytime after I clicked on the "connect wallet", it just stucked there as "initializing wallet connection"; it never proceeded (as referred to in the picture attached). Can you teach me how to solve this problem?

Also, I saw a lot of people discussing on reddit and other social apps that after converting Nu or keep to T, they lost half of their assets. Can you let me know what happened?

Thanks,

**Comment by KlamdeMo-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Threshold SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by cygnusv** [comment]
Hi @Wangj20036, please ignore the previous responses as they don't belong to any real Threshold Network support. I just deleted them but I'm letting you know in case you saw them. Official support can be found only in the official Discord server. You can find the link to the server in the official website, never trust links posted in a public forum.

Having said that, we need more information regarding your specific problem. As said, please proceed to ask for support in our official discord server.
