### ISSUE TITLE
Checkpoints allows to delegate to 0x0, which unintended consecuences

### ISSUE THREAD

**Issue by ggrieco-tob** [threshold-network/solidity-contracts#24]
I'm in the process of investigating an issue related with delegation. It seems users can delegate tokens 0x0:

https://github.com/keep-network/coverage-pools/blob/fde97c445bcff2bbc9e563dd33ba24fcfecb7f05/contracts/UnderwriterToken.sol#L135-L144

This will cause to their voting power to disappear (since dst == 0x0):

https://github.com/threshold-network/solidity-contracts/blob/4d8ab316d8705cf0deaa0afee7c88f5757937f56/contracts/governance/Checkpoints.sol#L114-L142

However, their balance will be available (and the voting power can be easily recovered if they delegate to an non zero address).  Later, the same user could burn their tokens (which looks like a transfer to 0x0):

https://github.com/keep-network/coverage-pools/blob/fde97c445bcff2bbc9e563dd33ba24fcfecb7f05/contracts/UnderwriterToken.sol#L106-L127

This will trigger a call to `writeCheckpoint(_totalSupplyCheckpoints, subtract, safeAmount);`  which I'm not sure if it is necessary.

**Comment by pdyraga** [comment]
Hey @cygnusv, what do we do about this one?

**Comment by cygnusv** [comment]
I don't see what's the issue from the perspective of the Checkpoints abstract contract. The call to `writeCheckpoint(_totalSupplyCheckpoints, subtract, safeAmount)` is needed to decrease the checkpoint of the total supply, which is unrelated to the users' checkpoints for their delegated voting power.
