### ISSUE TITLE
T token and VendingMachines deployment

### ISSUE THREAD

**Issue by pdyraga** [threshold-network/solidity-contracts#53]
Team | Address
------------ | -------------
**Deployment Team** | `0x123694886DBf5Ac94DDA07135349534536D14cAf`
**Threshold Council** | `0x9f6e831c8f8939dc0c830c6e492e7cef4f9c2f5f`

# Prerequisites 
- [x] KEEP community decision on pausing the inflation (https://forum.keep.network/t/proposal-pause-keep-inflation-to-calculate-token-factor-for-threshold/375)
- [x] NU community decision on pausing the inflation (https://dao.nucypher.com/t/2-halt-nu-inflation-indefinitely-remove-voting-endpoints-from-stakingescrow/329)
- [x] Wrapped token allocation calculated for KEEP<>T vending machine (`wrappedTokenAllocation = 940795010800000000000000000`)
- [x] Wrapped token allocation calculated for NU<>T vending machine (`wrappedTokenAllocation = 1380688920644254727736959922`)
- [x] Deployment scripts updated to follow this procedure (https://github.com/threshold-network/solidity-contracts/pull/55)

# Deploy smart contracts
- [x] Tag `v1.0.0` in `threshold-network/solidity-contracts`
- [x] Sign `v1.0.0` commit hash
- [x] Deploy `T` token contract (address: `0xCdF7028ceAB81fA0C6971208e83fa7872994beE5`)
- [x] Deploy KEEP<>T `VendingMachine` contract with the following parameters (address: `0xE47c80e8c23f6B4A1aE41c34837a0599D5D16bb0`):
  - `_wrappedToken`: `0x85eee30c52b0b379b046fb0f85f4f3dc3009afec`
  - `_tToken`: `T.address`
  - `_wrappedTokenAllocation`: `940795010800000000000000000`
  - `_tTokenAllocation`: `4500000000000000000000000000`
- [x] Deploy NU<>T `VendingMachine` contract with the following parameters (address: `0x1CCA7E410eE41739792eA0A24e00349Dd247680e`):
  - `_wrappedToken`: `0x4fE83213D56308330EC302a8BD641f1d0113A4Cc`
  - `_tToken`: `T.address`
  - `_wrappedTokenAllocation`: `1380688920644254727736959922`
  - `_tTokenAllocation`: `4500000000000000000000000000`
- [x] Set up Threshold Council multisig contract (address: `0x9f6e831c8f8939dc0c830c6e492e7cef4f9c2f5f`)
- [x] Threshold Council signed TX lowering threshold from 9/9 to 7/9 (TX: https://etherscan.io/tx/0x3f84fdbb6ef1f50456e4ec6ce9f85e8c9b152d7ba8ba1379549224ad075881df) 
 - [x] Transfer ownership of `T` contract to Threshould Council (TX: https://etherscan.io/tx/0xd554fbceff6417cd35d74e67fa16ac8dc922d901ae5869096a8c77b59fa0fdad)

 # Etherscan verification
- [x] Verify `T` contract
- [x] Verify `VendingMachine` contract

# Package publication
- [x] Publish v1.0.0 package of `threshold-network/solidity-contracts` to NPM

# Release notes
- [x] Publish `solidity/v1.0.0` release notes in `threshold-network/solidity-contracts`

**Comment by nkuba** [comment]
>  Deploy T token contract (address: 0x...)

`yarn deploy --network mainnet --tags T`

> Deploy KEEP<>T VendingMachine contract with the following parameters: 

`yarn deploy --network mainnet --tags VendingMachineKeep`

> Deploy NU<>T VendingMachine contract with the following parameters: 

`yarn deploy --network mainnet --tags VendingMachineNuCypher`

> Transfer ownership of T contract to Threshould Council (TX: 0x...)
`yarn deploy --network mainnet --tags TransferOwnershipT`

**Comment by cygnusv** [comment]
We can't deploy vending machines until T supply (at least 4.5 B) is minted. Alternatively we can remove that restriction from vending machine constructor.

**Comment by pdyraga** [comment]
No longer a draft, we will start executing this procedure at Dec 31, 2021, 10:00 CET
