### ISSUE TITLE
stakeNu function referencing Keep contract instead of Nu contract

### ISSUE THREAD

**Issue by alexfisher** [threshold-network/solidity-contracts#68]
Forgive me if this is line is correct, but I just happened to notice the stakeNu function is checking keepStakingContract for legacy staker delegation info.  Should it be nucypherStakingContract?

https://github.com/threshold-network/solidity-contracts/blob/d203d18912385bd86a3d7540e16dc706a4e32082/contracts/staking/TokenStaking.sol#L355

**Comment by vzotova** [comment]
This line is correct, checks if NU staker can use address because this address (staking provider) theoretically can be already used in Keep

**Comment by hamid0785** [comment]
,mhack hack githup hack discord hack
