### ISSUE TITLE
Risk of being frontrun when calling "notifyKeepStakeDiscrepancy" and "notifyNuStakeDiscrepancy"

### ISSUE THREAD

**Issue by arenoide** [threshold-network/solidity-contracts#83]
Since anyone can call the "notifyKeepStakeDiscrepancy" and "notifyNuStakeDiscrepancy" functions and take the notification reward, users run the risk when calling these functions that a bot will frontrun them, so ultimately users will not notify these discrepancies, since they will simply waste the ether for the transaction.

**Comment by vzotova** [comment]
Fixed in #153
